kaminari を使ってページング処理を実装する
shugoStr/fjord-books_app pull request #2
Opened 2021-11-21 08:14 UTC by shugoStr

プラクティスの課題を提出いたします。
ご確認よろしくお願いいたします！

2021-11-26 04:20 UTC, u1tnk requested changes

2021-11-26 04:20 UTC, u1tnk commented on app/controllers/books_controller.rb
> +    Book.order(:id).page(params[:page]).per(number)
この量ならメソッドにせずにそのまま書いた方が分かりやすいと思います。
`page(3)`だけ見ると何をやってるか情報が少なすぎて分かりませんし。
また、perの値は一つのアプリでは同じ事が多い(設定で変わったりすれば別ですが)ので定数で良いでしょう。
`BOOK_PER = 3` 
とか定義して使うと良いですね。

2021-12-01 13:13 UTC, shugoStr commented on app/controllers/books_controller.rb
> +    Book.order(:id).page(params[:page]).per(number)
確かに処理の内容も分かりづらく、余計なメソッド化でした。。
定数設定、なるほどです。ありがとうございます！🙏

2021-12-02 12:25 UTC, u1tnk approved these changes

2022-02-02 09:40 UTC, shugoStr commented
マージします

2022-02-02 09:40 UTC, merged